[tool.poetry]
name = "my-package"
version = "0.1.0"
description = "My package description"
authors = ["gowridurgad <gowridurga.d@github.com>"]

[tool.poetry.dependencies]
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
