name: poetryTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'
    - name: Set Poetry Python version
      run: poetry env use ${{ steps.setup-python.outputs.python-path }}python
    - run: poetry install
    
