name: poetryTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
       python-version: '3.10.9'
    - name: Install Poetry
      run: |
        pipx install poetry
        poetry env use python3.10.9
    - name: Install dependencies
      run: poetry install
 
   
    
