name: poetryTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
    - name: Check Poetry Python version
      run: poetry env info
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'poetry'
    - run: poetry install
    - name: Check Poetry Python version
      run: poetry env info
    
