name: poetryTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
       python-version: '3.10.9'
       cache: 'poetry'
    - run: |
       python -m pip install poetry
    - name: Check Poetry Python version
      run: poetry env info
    - name: Install dependencies
      run: poetry install
    - name: Lock dependencies
      run: |
        poetry lock --no-update


   
    
