name: poetryTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Setup Python
       id: setup-python
       uses: actions/setup-python@v5
       with:
        python-version: '3.10.9'
        cache: 'poetry'
     - name: Install poetry
       run: pipx install poetry
     - name: Set poetry Python interpreter
       run: poetry env use python${{ steps.setup-python.outputs.python-version }}
     - run: poetry install
 
   
    
