name: poetryTest1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Python path in Poetry
      run: poetry env use ${{ steps.setup-python.outputs.python-path }}python 
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
       python-version: '3.10.9'
       cache: 'poetry'
    - run: poetry install
    - name: Check Poetry Python version
      run: poetry env info
    - name: Install dependencies
      run: poetry install
    - name: Lock dependencies
      run: |
        poetry lock --no-update


   
    
