name: Setup and Run Flask Server

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - master  # Run workflow on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
       matrix:
          version: [3.7,3.10,3.12,3.8.10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version}} # Set Python version
