name: Summary Check

on:
  workflow_dispatch:

jobs:
  UbuntuCheck:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip --no-warn-script-location
    - name: Install dependencies
      run: pip install -r requirements.txt 

  MacosCheck:
    needs: UbuntuCheck
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip --no-warn-script-location
    - name: Install dependencies
      run: pip install -r requirements.txt
