name: Python package

on:
 workflow_dispatch:

jobs:
  install-with-extras:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip --no-warn-script-location
    - name: Install dependencies
      run: |
        pip3 install poetry --no-warn-script-location
        poetry install --all-extras
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
    
   
