name: summaryCheck

on:
  workflow_dispatch:

jobs:
  MacosCheck:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Changed Python version to latest stable release
    - name: Install dependencies
      run: pip install -r requirements.txt # Assuming you have a requirements.txt file with all dependencies
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

  
  

  
