name: Python package

on:
 workflow_dispatch:

jobs:
  install-with-extras:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Upgrade pip
      run: python3.10 -m pip install --upgrade pip

    - name: Check pip version after upgrade
      run: pip --version
    
    - name: Install dependencies
      run: |
        pip3 install poetry
        poetry install --all-extras
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}

  install-without-extras:
    needs: install-with-extras
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    
    - name: Install dependencies
      run: |
        pip3 install poetry
        poetry install
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
