name: Summary Check

on:
  workflow_dispatch:

jobs:
  macosCheck:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip install -r requirements.txt

  
